# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "in-byte-order"
theme = "apollo"
taxonomies = [{ name = "tags" }]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# Sets the color theme for the blog.
theme = "toggle"
# Enables or disables the table of contents for posts.
toc = true
socials = [
    # Configure socials here
    { name = "github", url = "https://github.com/mohamedeliwa", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/mohammedredaa/", icon = "linkedin" },
]
menu = [
    # Configure menu bar here
    # { name = "/posts", url = "/posts", weight = 1 },
    # { name = "/projects", url = "/projects", weight = 2 },
    # { name = "/about", url = "/about", weight = 3 },
    # { name = "/tags", url = "/tags", weight = 4 },
]

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14
